### ISSUE TITLE
No signal in Jaero

### ISSUE THREAD

**Issue by thebaldgeek** [jeroenbeijer/SDRReceiver#4] opened 2021-08-01 15:08 UTC
Greetings.   
I have spent around 4-5 hours working with the software and cant get any signal into Jaero.    
Here is my current test configuration ini file:    
```
sample_rate=1920000
center_frequency=1545600000
zmq_address=tcp://*:6004
mix_offset=0

#auto_start=1
#auto_start_tuner_idx=0

#remote_rtl=127.0.0.1:1234

#valid tuner gains r82xx_gains[] = { 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496 };
tuner_gain=496
correct_dc_bias=0
mix_offset=0

[main_vfos]
size=1
1\frequency=1545120000
1\out_rate=240000


[vfos]
size=2
1\frequency=1545014429
1\gain=4
1\data_rate=600
1\filter_bandwidth=0
1\topic=VFO41
2\frequency=1545029412
2\gain=4
2\data_rate=1200
2\filter_bandwidth=0
2\topic=VFO42
```
   
 The ini file is in the same directory as sdrreciver.exe. I start the command from a power shell:    
 ```.\SDRReceiver.exe -s sdr_54w_test.ini```    
I am testing with 54W satellite.    
![sdrtest](https://user-images.githubusercontent.com/7385116/127775607-27e3bee8-c680-4174-84ac-aa3cba23e137.png)

Other than the obvious question of why no output, My other question is how to do we know the VFO tuned frequency?   
![sdrfreq](https://user-images.githubusercontent.com/7385116/127775681-17d97407-87b2-498a-b8aa-24a73e99b885.png)
Lastly why are your 54w sample ini file channel frequencies 'wrong'?    
They should be as follows?    
```
1545.0300 GES:43 600
1545.0350 GES:44 1200
1545.0400 GES:43 600
1545.0450 GES:44 1200
1545.0950 GES:44 600
1545.1000 GES:02 600
1545.1350 GES:44 600
1545.1400 GES:43 1200
1545.1790 GES:43 600
1546.0550 GES:44 10500
1546.0700 GES:43 10500
1546.0850 GES:44 10500
```
  
I currently track 4 satellites on L-Band, 98W, 143E, 54W and 25E and 2 on C-Band, 98W and 143E. Looking forward to improved decode rates and better long term stability with this software.   
    
 Thanks for your help.

**Comment by jeroenbeijer** [comment] 2021-08-01 19:07
Hi!

Little tied up atm but will check asap. That locking bw looks weird in jaero so I wonder if something went wrong there.

Inmarsat have dropped a number of 600 and 1200 channels off 54w recently on two seperate occaisions, I think there are only 2 x 600 and 2 x 1200 bps left. There are no GES:02 channels on 54W.

Get back to you soon

/Jeroen



Sent from my Galaxy



-------- Original message --------
From: thebaldgeek ***@***.***>
Date: 01/08/2021 17:09 (GMT+01:00)
To: jeroenbeijer/SDRReceiver ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeroenbeijer/SDRReceiver] No signal in Jaero (#4)


Greetings.
I have spent around 4-5 hours working with the software and cant get any signal into Jaero.
Here is my current test configuration ini file:

sample_rate=1920000
center_frequency=1545600000
zmq_address=tcp://*:6004
mix_offset=0

#auto_start=1
#auto_start_tuner_idx=0

#remote_rtl=127.0.0.1:1234

#valid tuner gains r82xx_gains[] = { 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496 };
tuner_gain=496
correct_dc_bias=0
mix_offset=0

[main_vfos]
size=1
1\frequency=1545120000
1\out_rate=240000


[vfos]
size=2
1\frequency=1545014429
1\gain=4
1\data_rate=600
1\filter_bandwidth=0
1\topic=VFO41
2\frequency=1545029412
2\gain=4
2\data_rate=1200
2\filter_bandwidth=0
2\topic=VFO42


The ini file is in the same directory as sdrreciver.exe. I start the command from a power shell:
.\SDRReceiver.exe -s sdr_54w_test.ini
I am testing with 54W satellite.
[sdrtest]<https://user-images.githubusercontent.com/7385116/127775607-27e3bee8-c680-4174-84ac-aa3cba23e137.png>

Other than the obvious question of why no output, My other question is how to do we know the VFO tuned frequency?
[sdrfreq]<https://user-images.githubusercontent.com/7385116/127775681-17d97407-87b2-498a-b8aa-24a73e99b885.png>
Lastly why are your 54w sample ini file channel frequencies 'wrong'?
They should be as follows?

1545.0300 GES:43 600
1545.0350 GES:44 1200
1545.0400 GES:43 600
1545.0450 GES:44 1200
1545.0950 GES:44 600
1545.1000 GES:02 600
1545.1350 GES:44 600
1545.1400 GES:43 1200
1545.1790 GES:43 600
1546.0550 GES:44 10500
1546.0700 GES:43 10500
1546.0850 GES:44 10500


I currently track 4 satellites on L-Band, 98W, 143E, 54W and 25E and 2 on C-Band, 98W and 143E. Looking forward to improved decode rates and better long term stability with this software.

Thanks for your help.

**Comment by jeroenbeijer** [comment] 2021-08-01 22:46
It looks like something is off in the latest jaero release, I did a quick code compare but could not spot anything obvious but you can see the locking bandwidth in your screenshot is a little too narrow for a 600 bps channel and the audio spectrum seems to be wider than it should be for 600 bps channel in non-wideband (12Khz sample rate). I will ping jonti and let him know. 

![image](https://user-images.githubusercontent.com/31091871/127787363-e463cf53-643a-4731-8ffb-0c145feac1ec.png)

In the meantime if you want to get running you can download a jaero copy from my fork that should be ok, just tried it and it ran ok with your ini file. 

https://github.com/jeroenbeijer/JAERO/releases (check under assets and the development build I just ran around midnight CET).

I just double checked on 54W and there are now only 4 x 600 bps channels left. I will update the 54W all ini file. Note that this has the "atlantic" spot beams included that may be quite weak where you are. If you don't want to bother with those voice channels you would be better off with a 1536000 sample rate I guess. These are the 4 x 600 channels left:

1\frequency=1545014429
1\gain=4
1\data_rate=600
1\filter_bandwidth=0
1\topic=VFO41
2\frequency=1545029412
2\gain=4
2\data_rate=600
2\filter_bandwidth=0
2\topic=VFO42
3\frequency=1545134635
3\gain=4
3\data_rate=600
3\filter_bandwidth=0
3\topic=VFO43
4\frequency=1545194731
4\gain=4
4\data_rate=600
4\filter_bandwidth=0
4\topic=VFO44

The VFO tuned center frequency is what the you enter in the INI file. It goes through multiple mixers but at end of it, what you enter in the INI file is what you get in jaero. I suppose this may differ from how SDR# or SDR Console displays the VFO frequency, not entirely sure. I will add a 98W ini as well.

**Comment by thebaldgeek** [comment] 2021-08-02 00:08
Thanks so much for burning the midnight oil and helping me get going.    
There was no difference between the two Jaeros. Both showed Red volume and two grey LEDs with no signal bumps with your 4 VFO ini file.         
I then did as you suggested and ran with 1536000 sample rate and everything started working as expected.    
I am using an RTLSDRv3. The flatish silver one, so I am not sure why the sample rate change made the difference.    
I am running your midnight Jaero build since it seems better setup, but both Jaero versions were giving me some decodes.    
The other big difference is I was following your readme and leaving the gain at 496. The volume led was RED and the waveform in Jaero did not look good at all.    
When running with other audio SDR software, I ran the gain at 14.4, so changed SDRReciver ini to be the same and Volume LED is now green and the wave form looks much better.     
     
 
![sdrreciverworking54w](https://user-images.githubusercontent.com/7385116/127789186-c33f9f16-91bc-4e64-8e51-654c18ab76b9.PNG)
     
 Thankyou also for explaining that the frequencies in the ini file are the center of each channel. This information will be critical for me when I try and write the ini file for the 98W 1200 burst channels.    
![sdrreciver1200fun](https://user-images.githubusercontent.com/7385116/127789391-2b9757fe-c3a1-4eb7-96bf-071544f5ecba.PNG)
      
Any advice other than writing down the center frequency of each channel? They all get used every day.    
     
     Once again, thanks for the software, it is so nice to see the data flow with zero CRC errors and dropped frame messages.

**Comment by jontio** [comment] 2021-08-02 04:39
The first screenshot in this thread is odd. It looks as if the spectrum is displaying up to 30kHz so that would mean a 60kHz sample rate. For ZMQ input at 600bps JAERO will adjust the bandwidth depending on what SDRReceiver sends it as, but I thought that only 12kHz and 48kHz where supported by JAERO. I tried SDRReceiver sending at 12kHz and 48kHz and things seem to be normal...

![image](https://user-images.githubusercontent.com/13667843/127804268-056ee320-054c-42cd-b114-1248f0d20168.png)
![image](https://user-images.githubusercontent.com/13667843/127804686-e6af9b55-4560-4104-87ba-b343cdd77e6c.png)

So I'm not sure how the spectrum display goes up to 30kHz in the first screenshot, I can't seem to reproduce it.

**Comment by jontio** [comment] 2021-08-02 04:46
ah got it...

![image](https://user-images.githubusercontent.com/13667843/127805217-dc3e87bf-59de-40de-a29d-b36874449bb3.png)

Yup SDRReceiver when the samplerate isn't supported such as 1920000 the rate as advertised to JAERO is also not right. In this case the rate is advertised as 60kHz rather than 12kHz for the bit rate as set in the ini file as 600. This is the second time this has got me. I'll add some checking to the sample rate in SDRReceiver to fail on unsupported sample rates as this going to catch others out.

**Comment by jontio** [comment] 2021-08-02 05:05
Oh 15360000 and 1920000 are both supported rates. So something is going on in SDRReceiver than when 1920000 is selected the advertised rate given to JAERO is 60kHz rather than 12kHz given an ini setting rate of 600.

**Comment by jeroenbeijer** [comment] 2021-08-02 08:40
The CBand side is trickier I guess. I setup an ini file for 143E using a recorded IQ dump which made it a little easier. I would try to setup a few of the 10500 burst T channels first and compare the frequencies between SDR Console and what you need to put in the ini file. Once you have that I suppose you can calculate what the 1200 burst channel frequencies should be. I would also focus on the T channels there and not bother with the R channels, don't think there is any useful information there from what I recall.

**Comment by jeroenbeijer** [comment] 2021-08-09 14:51
closing this, sdr should be sending proper rate info now.

**Closed by jeroenbeijer** 2021-08-09 14:51 UTC
